#pragma once

#define DFU_FLASH_PAGE_SIZE (1024) //todo

#define APP_MAX_SIZE (300 * 1024ul)

#define SOFT_DEV_START_ADDR (0x1000UL)
#define BOOT_START_ADDR (0xe0000UL)
#define APP_START_ADDR (0x27000UL)
#define DFU_BAK_START_ADDR (APP_START_ADDR + APP_MAX_SIZE)

#define DFU_APP_INFO_ADDR (DFU_BAK_START_ADDR + APP_MAX_SIZE + DFU_FLASH_PAGE_SIZE)
